name: atmt-sdv

services:
  postgres_db:
    image: postgres:16
    container_name: atmt-sdv-postgres_db-1
    environment:
      POSTGRES_USER: atmt_admin
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: atmt_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
