"""Add architectures and vehicle_types filters

Revision ID: 217183bb6577
Revises: c9b67d607d7d
Create Date: 2026-05-24 00:59:47.579059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '217183bb6577'
down_revision = 'c9b67d607d7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ref_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('architectures', sa.ARRAY(sa.Text()), nullable=True))

    with op.batch_alter_table('ref_threats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_types', sa.ARRAY(sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('architectures', sa.ARRAY(sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ref_threats', schema=None) as batch_op:
        batch_op.drop_column('architectures')
        batch_op.drop_column('vehicle_types')

    with op.batch_alter_table('ref_assets', schema=None) as batch_op:
        batch_op.drop_column('architectures')

    # ### end Alembic commands ###
