"""add threats table

Revision ID: 46ad4de4b8a3
Revises: a631df60c1d5
Create Date: 2026-05-13 00:18:09.596712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46ad4de4b8a3'
down_revision = 'a631df60c1d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('ref_threat_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.String(length=100), nullable=False),
    sa.Column('flow_id', sa.String(length=100), nullable=True),
    sa.Column('stride_category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_ref', sa.String(length=100), nullable=True),
    sa.Column('impact_safety', sa.SmallInteger(), nullable=False),
    sa.Column('impact_financial', sa.SmallInteger(), nullable=False),
    sa.Column('impact_operational', sa.SmallInteger(), nullable=False),
    sa.Column('impact_privacy', sa.SmallInteger(), nullable=False),
    sa.Column('feasibility', sa.SmallInteger(), nullable=False),
    sa.Column('risk_score', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('treatment', sa.String(length=20), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('control_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('is_baseline_modified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ref_threat_id'], ['ref_threats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('threats')
    # ### end Alembic commands ###
