"""Add vehicle_categories to ref_assets

Revision ID: a457f550e761
Revises: ece60a63528f
Create Date: 2026-05-31 22:18:38.935179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a457f550e761'
down_revision = 'ece60a63528f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ref_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_categories', sa.ARRAY(sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ref_assets', schema=None) as batch_op:
        batch_op.drop_column('vehicle_categories')

    # ### end Alembic commands ###
