"""add reference tables: assets, threats, controls

Revision ID: ab18685098e2
Revises: 2ba38f8ba84a
Create Date: 2026-05-05 01:15:46.417670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab18685098e2'
down_revision = '2ba38f8ba84a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controls_library',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('applies_to_stride', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('applies_to_protocols', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('feasibility_reduction', sa.SmallInteger(), nullable=True),
    sa.Column('source_ref', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ref_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('interface_types', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('data_types', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('physical_accessibility', sa.String(length=30), nullable=True),
    sa.Column('asil_level', sa.String(length=1), nullable=True),
    sa.Column('default_safety', sa.SmallInteger(), nullable=True),
    sa.Column('default_privacy', sa.SmallInteger(), nullable=True),
    sa.Column('flags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('vehicle_types', sa.ARRAY(sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ref_threats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stride_category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_ref', sa.String(length=100), nullable=True),
    sa.Column('trigger_protocols', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('trigger_categories', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('trigger_flags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('default_impact', sa.SmallInteger(), nullable=True),
    sa.Column('default_feasibility', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ref_threats')
    op.drop_table('ref_assets')
    op.drop_table('controls_library')
    # ### end Alembic commands ###
