"""Add asset_name to Threat

Revision ID: ece60a63528f
Revises: 217183bb6577
Create Date: 2026-05-24 11:37:37.235512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ece60a63528f'
down_revision = '217183bb6577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_name', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threats', schema=None) as batch_op:
        batch_op.drop_column('asset_name')

    # ### end Alembic commands ###
